# Generated by Django 3.2.4 on 2021-08-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer', models.CharField(max_length=12)),
                ('presentations', models.CharField(max_length=12)),
                ('duration', models.PositiveSmallIntegerField(max_length=10)),
                ('course_material', models.FileField(max_length=10, upload_to='')),
                ('results', models.PositiveSmallIntegerField(max_length=10)),
                ('id_Number', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=10)),
                ('Unit_Name', models.CharField(max_length=10)),
            ],
        ),
    ]
