# Generated by Django 3.2.4 on 2021-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210820_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_material',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
