# Generated by Django 3.2.4 on 2021-08-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=12)),
                ('id_Number', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=10)),
                ('photo', models.ImageField(max_length=10, upload_to='')),
                ('trainer_cv', models.FileField(max_length=10, upload_to='')),
                ('age', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.PositiveIntegerField(max_length=13)),
                ('Unit_Name', models.CharField(max_length=10)),
                ('Bank_account', models.CharField(max_length=14)),
            ],
        ),
    ]
