# Generated by Django 3.2.4 on 2021-08-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='photo',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Bank_account',
            field=models.CharField(blank=True, default=29, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Unit_Name',
            field=models.CharField(blank=True, default=23, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='age',
            field=models.CharField(blank=True, default=24, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, default=30, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(blank=True, default=23, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(blank=True, default=30, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='id_Number',
            field=models.CharField(blank=True, default=35, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(blank=True, default=20, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phoneNumber',
            field=models.PositiveIntegerField(blank=True, default=41, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profession',
            field=models.CharField(blank=True, default=45, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_cv',
            field=models.FileField(blank=True, default=35, max_length=10, null=True, upload_to=''),
        ),
    ]
