# Generated by Django 3.2.4 on 2021-08-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Big_sister',
            field=models.CharField(blank=True, default=50, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, default=40, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, default=35, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='county',
            field=models.CharField(blank=True, default=50, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default=30, max_length=35, null=50),
            preserve_default=50,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, default=40, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_report',
            field=models.FileField(blank=True, default=40, max_length=15, null=34, upload_to=''),
            preserve_default=34,
        ),
        migrations.AddField(
            model_name='student',
            name='mentors_name',
            field=models.CharField(blank=True, default=47, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phoneNumber',
            field=models.PositiveIntegerField(blank=True, default=45, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration',
            field=models.PositiveSmallIntegerField(default=39, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(blank=True, default=50, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id_passport',
            field=models.CharField(blank=True, default=50, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=25, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=40, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, default=30, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default=20, max_length=10, null=True),
        ),
    ]
