# Generated by Django 3.2.4 on 2021-08-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_venue', models.CharField(max_length=10)),
                ('Event_duration', models.DateTimeField(max_length=12)),
                ('Event_goal', models.CharField(max_length=13)),
                ('Event_signed_by', models.CharField(max_length=12)),
                ('Event_date', models.DateField(max_length=10)),
                ('Event_atendee', models.IntegerField(max_length=10)),
                ('Event_name', models.CharField(max_length=12)),
            ],
        ),
    ]
