# Generated by Django 3.2.4 on 2021-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_auto_20210820_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='Event_atendee',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='Event_date',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='Event_duration',
            field=models.DateTimeField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='Event_goal',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='Event_name',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='Event_signed_by',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='Event_venue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
